#!/bin/sh
#

LOGFILE="/var/log/MythTV/MythTV.log"
MYTH_HOME="/usr/pbi/mythtv-`uname -m`"

# Check if Xvfb is enabled in config file created by GUI
XVFB_ENABLE=`grep Xvfb ${MYTH_HOME}/etc/mythtv.conf | sed -e "s,Xvfb_Enable= ,,"`
echo $XVFB_ENABLE

# Need to check if Xvfb is running from another plugin and use that display
RUNNING_DISPLAY_ID=""
RUNNING_DISPLAY_ID=`pgrep -l -f Xvfb | sed -e "s,^[0-9].* *Xvfb ,," -e "s,-screen .*,,"`

# Retreive which MythTV service user wants started from etc/mythtv.conf
# 1 = mythtv-setup 2 = mythtvbackend 3 = mythttvfrontend

Myth_Service=`grep "MythService= " ${MYTH_HOME}/etc/mythtv.conf | sed -e "s,MythService= ,,"`
echo "Myth_Service = " ${Myth_Service}


#
 # Check if mythtv-setup is enabled in config file created by GUI
 #Myth_Setup_ENABLE=`grep MythTV-Setup ${MYTH_HOME}/etc/mythtv.conf | sed -e "s,MythTV-Setup_Enable= ,,"`
 #echo $Myth_Setup_ENABLE

 # Check if mythtv-backend is enabled in config file created by GUI
 #Myth_Backend_ENABLE=`grep MythTV-Backend ${MYTH_HOME}/etc/mythtv.conf | sed -e "s,MythTV-Backend_Enable= ,,"`
 #echo $Myth_Backend_ENABLE
#

# Get X DISPLAY setting from config file created by GUI
XDISPLAY=`grep "X11_Display= " ${MYTH_HOME}/etc/mythtv.conf | sed -e "s,X11_Display= ,,"`
#echo $XDISPLAY
DISPLAY=${XDISPLAY}
echo $DISPLAY

# EXAMPLE setting DISPLAY for bash and csh
# export DISPLAY=:1
# setenv DISPLAY :1
# export DISPLAY=192.168.2.1:0.0
# setenv DISPLAY 192.168.2.1:0.0
#

# EXAMPLE of VNC using password authentication
# exec x11vnc -noshm -usepw -nevershared -forever -display :1

if [ $XVFB_ENABLE -eq 1 ]; then

    export DISPLAY=:1

    if [ -n "$RUNNING_DISPLAY_ID" ]; then
        echo "Existing Xvfb Display, using that." ${RUNNING_DISPLAY_ID}
        DISPLAY=${RUNNING_DISPLAY_ID}
        export DISPLAY
    fi

# If Xvfb is not already running, then start it.

    if [ -z `pgrep Xvfb` ]; then
        exec ${MYTH_HOME}/bin/Xvfb ${DISPLAY} -screen 0 1280x1024x16 &
    fi

# If x11vnc is not already running, then start it.

    if [ -z `pgrep x11vnc` ]; then
        exec ${MYTH_HOME}/bin/x11vnc -noshm -nevershared -forever -display :1 &
    fi

    if [ -z `pgrep fluxbox` ]; then
        # Need to make sure Xvfb has started before starting fluxbox
        sleep 1
        exec ${MYTH_HOME}/bin/fluxbox -d :1 &
    fi
fi

if [ $XVFB_ENABLE -ne 1 ]; then
    killall Xvfb x11vnc fluxbox
    export DISPLAY
    echo "Starting MythTV on DISPLAY:" >> $LOGFILE
    echo $DISPLAY >> $LOGFILE
fi

# Mythtv-setup
if [ $Myth_Service -eq 1 ]; then
    export HOME=/usr/pbi/mythtv-`uname -m`/etc/home/mythtv
    exec ${MYTH_HOME}/bin/mythtv-setup &
fi

# MythBackend - Need to Fix above, don't need Xvfb, x11vnc, or fluxbox running for backend.
# Added test in mysql-server to start MythBackend and only branch to sbin/mythtv for other services needing X11

#if [ $Myth_Service -eq 2 ]; then
#    ${MYTH_HOME}/etc/rc.d/mythbackend onestart
#    #exec ${MYTH_HOME}/bin/mythbackend &
#fi

# MythFrontend (NOT ENABLED YET, need both front & back enabled for this)

if [ $Myth_Service -eq 3 ]; then

# Check if backend is running before starting it here
    if [ -z `pgrep mythbackend` ]; then
        ${MYTH_HOME}/etc/rc.d/mythbackend onestart
    fi

    exec ${MYTH_HOME}/bin/mythfrontend &
fi

# MythWelcome (NOT ENABLED YET, need both front & back enabled for this)

if [ $Myth_Service -eq 4 ]; then

# Check if backend is running before starting it here
    if [ -z `pgrep mythbackend` ]; then
        ${MYTH_HOME}/etc/rc.d/mythbackend onestart
    fi
    exec ${MYTH_HOME}/bin/mythwelcome &
fi
